import type { ThemeDefinition } from "vuetify";

export const MAIN_THEME = "mainTheme";
export const mainTheme: ThemeDefinition = {
  dark: false,
  colors: {
    primary: "#b22d00",
    "on-primary": "#ffffff",
    "primary-container": "#ffdacf",
    "on-primary-container": "#3c0800",
    secondary: "#77574e",
    "on-secondary": "#ffffff",
    "secondary-container": "#ffdacf",
    "on-secondary-container": "#2c160f",
    tertiary: "#6b5d2f",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#f5e1a6",
    "on-tertiary-container": "#231b00",
    error: "#ba1b1b",
    "on-error": "#ffffff",
    "error-container": "#ffdad4",
    "on-error-container": "#410001",
    background: "#ffdad4",
    "on-background": "#201a18",
    surface: "#fcfcfc",
    "on-surface": "#201a18",
    "inverse-surface": "#362f2d",
    "inverse-on-surface": "#fbeeeb",
    "inverse-primary": "#ffb49d",
    "surface-variant": "#f5ded8",
    "on-surface-variant": "#53433f",
    outline: "#86736e",
    shadow: "#000000",
  },
};

export const MAIN_DARK_THEME = "mainDarkTheme";
export const mainDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    primary: "#ffb49d",
    "on-primary": "#601400",
    "primary-container": "#882000",
    "on-primary-container": "#ffdacf",
    secondary: "#e7bdb2",
    "on-secondary": "#442a22",
    "secondary-container": "#5d3f37",
    "on-secondary-container": "#ffdacf",
    tertiary: "#d8c58d",
    "on-tertiary": "#3a2f04",
    "tertiary-container": "#53461a",
    "on-tertiary-container": "#f5e1a6",
    error: "#ffb4a9",
    "on-error": "#680003",
    "error-container": "#930006",
    "on-error-container": "#ffb4a9",
    background: "#442a26",
    "on-background": "#ede0dd",
    surface: "#201a18",
    "on-surface": "#ede0dd",
    "inverse-surface": "#ede0dd",
    "inverse-on-surface": "#362f2d",
    "inverse-primary": "#b22d00",
    "surface-variant": "#53433f",
    "on-surface-variant": "#d8c2bc",
    outline: "#a08c87",
    shadow: "#000000",
  },
};
